### ISSUE TITLE
10.1.0?

### ISSUE THREAD

**Issue by brianjmurrell** [Wuerfelbecher/jellyfin-rpm#10]
https://github.com/jellyfin/jellyfin/releases/tag/v10.1.0 has been released.  Can you push a build to copr?

Better yet, can you work with the jellyfin developers to get webhooks set up so that copr automatically builds release tags?

**Comment by Wuerfelbecher** [comment]
10.1.0 is pushed to COPR and tested (at least on fedora 29)

**Comment by Wuerfelbecher** [comment]
I'm already trying to get copr to auto-build Jellyfin but the results are not so great since the Jellyfin repo is so incredibly intertwined with all the submodules and it looks like [tito doesn't like submodules](https://github.com/dgoodwin/tito/issues/150) and the Makefile ~~wrote~~ hacked together didn't got much further.

Since copr happily builds SRPMs i will try to keep the copr repo updated with the build Upstream SRPMs util we get something working.

**Comment by brianjmurrell** [comment]
> Since copr happily builds SRPMs i will try to keep the copr repo updated with the Upstream SRPMs util we get something working.

What _Upstream SRPMs_ are you referring to?

Why not just make the `.copr/Makefile`->`srpm` target fetch that _Upstream SRPM_?

Then have the Jellyfin GitHub project push a webhook on tags to COPR.

**Comment by Wuerfelbecher** [comment]
The problem is that i have to build the SRPM first.
There are some build scripts in the Upstream repo if you clone the Jellyfin repo and run `./build fedora-package-x64 package` from the repo root you will get the RPM and SRPM in `../jellyfin-build/fedora-package-x64`.

The scripts there will do a `git submodule update --init` and create a source tarball for the SOURCES and build the whole thing in a docker container.

Also the git release tarballs don't have submodules, this seems like a recurring thing that nothing includes submodules.

**Comment by brianjmurrell** [comment]
> The problem is that i have to build the SRPM first.

Oh.  When you said _Upstream SRPMs_ I thought you were implying that along with the other builds that the Jellyfin devs are providing, they were also building SRPMs.  So to be clear, there are no SRPMs anywhere other than ones you build yourself?

> There are some build scripts in the Upstream repo..

But those same steps (or whatever steps you are doing locally to build an SRPM) won't work in a `.copr/Makefile`->`srpm` target?

**Comment by Wuerfelbecher** [comment]
> So to be clear, there are no SRPMs anywhere other than ones you build yourself?

now that you say it i found them :sweat_smile:: https://repo.jellyfin.org/releases/server/fedora/
I try getting this to work and bringing it upstream this weekend, should not be that hard with the SRPM.


To my defense the URL was not documented and until now i never tried guessing the URL.

**Comment by brianjmurrell** [comment]
The problem, now that I think about it, is that at the time of tagging you need the SRPM for the tagged release to be there because that's when you will get the webhook.

So you might have to build your own SRPM in a `.copr/Makefile`->`srpm` target after all.  But if the Jellyfin folks are doing it, it should be replicatable even (especially) without the use of a docker container even.

I don't know what they are doing in a docker container to build an SRPM but that seems like overkill.  Perhaps they are just using docker to get a Fedora system.  So you can dispense with that and just replicate the steps they are doing inside the Dockerfile in your `srpm` target.

**Comment by brianjmurrell** [comment]
I've got this worked out.

I have a patch to release-10.1.0 which builds jellyfin from SCM in COPR.  I have a webhook enabled for it in my jellyfin fork.  Once I squash my patch i will test tagging it and see if it auto-builds in COPR.

**Comment by brianjmurrell** [comment]
jellyfin/jellyfin#902
