### ISSUE TITLE
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

### ISSUE THREAD

**Issue by brianjmurrell** [Wuerfelbecher/jellyfin-rpm#5]
Since upgrading to jellyfin-3.5.2.gitf8a720d-2.fc29.x86_64 from jellyfin-3.5.2.gitf8a720d-1.fc29.x86_64 I'm getting:

```
Jan 05 11:54:18 pc systemd[1]: Started Jellyfin is a free software media system that puts you in control of managing and streaming your media..
Jan 05 11:54:19 pc jellyfin[12883]: Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Jan 05 11:54:19 pc systemd[1]: jellyfin.service: Main process exited, code=dumped, status=6/ABRT
Jan 05 11:54:19 pc systemd[1]: jellyfin.service: Failed with result 'core-dump'.
```

trying to start it.

I can't exactly see what changes went in between those two releases as there are no tags to indicate which revs were used to generate the corresponding RPMs.

**Comment by Wuerfelbecher** [comment]
That's strange since [this commit](https://github.com/Wuerfelbecher/jellyfin-rpm/commit/2ef283cfb528cc74868ed1d13a6fa29a812d279c#diff-29e39ef502901c2a126b8e035120c50a) addressed #2 which is mostly about the sudo policy so the jellyfin binarys should stay the same.

Im trying to reproduce this.

> I can't exactly see what changes went in between those two releases as there are no tags to indicate which revs were used to generate the corresponding RPMs.

I just started really using git/github to support jellyfin, so i have a lot to learn about how to git in a meaningful way.

**Comment by brianjmurrell** [comment]
> That's strange since [this commit](https://github.com/Wuerfelbecher/jellyfin-rpm/commit/2ef283cfb528cc74868ed1d13a6fa29a812d279c#diff-29e39ef502901c2a126b8e035120c50a) addressed #2 which is mostly about the sudo policy so the jellyfin binarys should stay the same.

Indeed.  That would be my expectation also.  Clearly something is amiss however.

> I just started really using git/github to support jellyfin, so i have a lot to learn about how to git in a meaningful way.

No worries.  This might not be useful/relevant for much longer as you are trying to upstream the RPM building, which is great.  But generally speaking, in your working copy (of the repo), at the point where you use the RPM specfile to push a build to COPR, it would be helpful to do a `git tag version` where _version_ is the RPM's _version-release_.  That way others can see exactly what was used to create the given binary RPM.

**Comment by Wuerfelbecher** [comment]
Interesting when i upgrade from jellyfin-3.5.2.gitf8a720d-1.fc29.x86_64 to jellyfin-3.5.2.gitf8a720d-2.fc29.x86_64 it crashes with the same error.

But when i upgrade to jellyfin-3.5.2.gitf8a720d-3.fc29.x86_64 the latest build from copr it works.

I have no idea where this comes from since in the gitf8a720d-3 i added the update-db.sh script, and fixed the spec file afterwards since CentOS had no `Recommends` tag and only the CentOS build where failing.

Can you please try to upgrade to jellyfin-3.5.2.gitf8a720d-3.fc29.x86_64 ?

**Comment by Wuerfelbecher** [comment]
I got the problem.

The [COPR build](https://copr-be.cloud.fedoraproject.org/results/wuerfelbecher/jellyfin/fedora-29-x86_64/00841754-jellyfin/builder-live.log) was successful, although dotnet stopped halfway through the build thus creating a corrupted RPM.

**Comment by brianjmurrell** [comment]
Eeeew.  That's ugly.  In any case jellyfin-3.5.2.gitf8a720d-3.fc29.x86_64 does work.
